advertisers:
  # Strategy: Target premium drama/documentaries; 30s cinematic; interactive pause ads.
  # Results: +22% brand consideration; 3.5x engagement; +18% dealership traffic; -30% cost/visitor.
  - name: "Luxury Auto Co"
    contact_email: "ads@luxauto.com"
    brand: "LuxAuto"
    agency_name: "Vision Media"
    campaigns:
      - name: "EV Awareness Launch"
        advertiser_id: null  # Will be set automatically during processing
        objective: "AWARENESS"
        status: "ACTIVE"
        target_cpm: 15.50
        dsp_partner: "DV360"
        flight:
          start_date: "2025-09-01"
          end_date: "2025-10-15"
        budget:
          amount: 120000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "EV Cinematic 30s"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 15.50
            pacing_pct: 100
            targeting:
              DEVICE: ["TV"]
              CONTENT_GENRE: ["DRAMA", "DOCUMENTARY"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/ev_30.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 30
  # Strategy: Comedy/reality alignment; humorous 15s; sequential storytelling; binge alignment.
  # Results: +15% awareness; +27% purchase intent; +12% sales lift; 2.3x ROI vs social.
  - name: "Crunchy Snacks"
    contact_email: "media@crunchysnacks.com"
    brand: "Crunchy"
    agency_name: "Snackable"
    campaigns:
      - name: "New Flavor Consideration"
        advertiser_id: null  # Will be set automatically during processing
        objective: "CONSIDERATION"
        status: "ACTIVE"
        target_cpm: 12.75
        dsp_partner: "DV360"
        flight:
          start_date: "2025-08-15"
          end_date: "2025-09-30"
        budget:
          amount: 60000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "Flavor 15s Spots"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 12.75
            pacing_pct: 100
            targeting:
              DEVICE: ["TV", "MOBILE"]
              CONTENT_GENRE: ["COMEDY", "REALITY"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/snack_15.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 15
  # Strategy: Financial/business docs; informative 20s; QR codes; evening/weekend daypart.
  # Results: +41% app downloads; -64% CPA; +18% avg deposit; 2.5x retention.
  - name: "NexBank"
    contact_email: "marketing@nexbank.com"
    brand: "NexBank"
    agency_name: "Growth Partners"
    campaigns:
      - name: "App Acquisition Q4"
        advertiser_id: null  # Will be set automatically during processing
        objective: "CONVERSION"
        status: "ACTIVE"
        target_cpm: 18.25
        dsp_partner: "DV360"
        flight:
          start_date: "2025-10-01"
          end_date: "2025-12-31"
        budget:
          amount: 40000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "App DL 15s"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 18.25
            pacing_pct: 100
            targeting:
              DEVICE: ["MOBILE", "DESKTOP"]
              CONTENT_GENRE: ["DOCUMENTARY", "BUSINESS"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/nexbank_15.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 15
  # Strategy: Travel/international content; visually striking 30s; weather-based targeting; mid-roll.
  # Results: +32% site visits; +28% booking conversion; +18% avg booking value; +0.7 nights stay.
  - name: "Sunset Resorts"
    contact_email: "ads@sunsetresorts.com"
    brand: "Sunset"
    agency_name: "TravelWave"
    campaigns:
      - name: "Shoulder Season Getaways"
        advertiser_id: null  # Will be set automatically during processing
        objective: "AWARENESS"
        status: "ACTIVE"
        target_cpm: 14.50
        dsp_partner: "DV360"
        flight:
          start_date: "2025-09-01"
          end_date: "2025-11-15"
        budget:
          amount: 80000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "Destinations 30s"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 14.50
            pacing_pct: 100
            targeting:
              DEVICE: ["TV"]
              CONTENT_GENRE: ["TRAVEL", "INTERNATIONAL"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/resort_30.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 30
  # Strategy: Fashion-forward shows/dramas; dynamic 15s; interactive browse; coordinated in-app launch.
  # Results: +37% brand searches; +24% e-comm traffic; +19% AOV; +22% new customers.
  - name: "Moda Retail"
    contact_email: "media@modaretail.com"
    brand: "Moda"
    agency_name: "StyleWorks"
    campaigns:
      - name: "Fall Collection Push"
        advertiser_id: null  # Will be set automatically during processing
        objective: "CONSIDERATION"
        status: "ACTIVE"
        target_cpm: 16.75
        dsp_partner: "DV360"
        flight:
          start_date: "2025-08-01"
          end_date: "2025-10-31"
        budget:
          amount: 50000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "Lookbook 15s"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 16.75
            pacing_pct: 100
            targeting:
              DEVICE: ["TV", "MOBILE"]
              CONTENT_GENRE: ["DRAMA", "LIFESTYLE"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/fashion_15.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 15
  # Strategy: Tech enthusiast/early adopter targeting; informative 30s demos; household targeting; sci-fi/tech adjacency.
  # Results: +44% awareness; +31% consideration; +26% partner traffic; 2.1x conversion rate vs YouTube.
  - name: "HomeTech"
    contact_email: "ads@hometech.com"
    brand: "HomeTech"
    agency_name: "Innovate Media"
    campaigns:
      - name: "Smart Home Launch"
        advertiser_id: null  # Will be set automatically during processing
        objective: "CONSIDERATION"
        status: "ACTIVE"
        target_cpm: 19.50
        dsp_partner: "DV360"
        flight:
          start_date: "2025-09-15"
          end_date: "2025-11-30"
        budget:
          amount: 70000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "Features 30s"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 19.50
            pacing_pct: 100
            targeting:
              DEVICE: ["CTV", "DESKTOP"]
              CONTENT_GENRE: ["SCIENCE_FICTION", "TECH"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/hometech_30.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 30
  # Strategy: Similar-genre targeting; trailer with countdown; frequency capping; heavy pre-release budget.
  # Results: +29% ticket intent; +34% trailer completion; 22% audience saw ad; 1.8x ROAS.
  - name: "Silver Screen Studios"
    contact_email: "media@silverscreen.com"
    brand: "SilverScreen"
    agency_name: "Blockbuster Media"
    campaigns:
      - name: "Theatrical Premiere Awareness"
        advertiser_id: null  # Will be set automatically during processing
        objective: "AWARENESS"
        status: "ACTIVE"
        target_cpm: 22.00
        dsp_partner: "DV360"
        flight:
          start_date: "2025-10-01"
          end_date: "2025-11-15"
        budget:
          amount: 90000
          type: "LIFETIME"
          currency: "USD"
        line_items:
          - name: "Trailer 30s"
            ad_format: "STANDARD_VIDEO"
            bid_cpm: 22.00
            pacing_pct: 100
            targeting:
              DEVICE: ["TV"]
              CONTENT_GENRE: ["ACTION", "THRILLER"]
              GEO_COUNTRY: ["US"]
            creatives:
              - asset_url: "https://cdn.example.com/assets/trailer_30.mp4"
                mime_type: "VIDEO/MP4"
                duration_seconds: 30
                
# ## Success Stories: Brands Winning with Netflix Ads
#
# Since the launch of Netflix’s advertising platform, numerous brands across different industries have
# achieved remarkable results with their campaigns. These success stories provide valuable insights and
# inspiration for marketers considering Netflix ads as part of their strategy.
#
# ### Automotive: Luxury Car Manufacturer
#
# **Campaign Objective:** Increase awareness and consideration for a new electric vehicle
# model among affluent professionals.
#
# **Strategy:**
#
# * Targeted viewers of premium drama series and documentaries
# * Utilized 30-second cinematic spots highlighting the vehicle’s design and technology
# * Implemented interactive pause ads with 360-degree vehicle exploration feature
#
# **Results:**
#
# * 22% increase in brand consideration among target audience
# * 3.5x higher engagement rate compared to traditional digital video
# * 18% lift in dealership website traffic
# * Cost per site visitor 30% lower than previous digital campaigns
#
# **Key Learning:** The immersive viewing environment of Netflix created a perfect showcase
# for the vehicle’s premium positioning, while the interactive elements drove deeper engagement with
# interested viewers.
#
# [Automotive Marketing](https://relevantaudience.com/) can benefit greatly from such immersive
# ad formats.
#
# ### Consumer Packaged Goods: Snack Food Brand
#
# **Campaign Objective:** Drive trial and purchase of a new product line among young adults.
#
# **Strategy:**
#
# * Targeted comedy and reality programming popular with 18-34 demographic
# * Developed a series of humorous 15-second spots showing unexpected situations
# * Implemented sequential storytelling across multiple ad exposures
# * Aligned with binge-watching sessions for repeated exposure
#
# **Results:**
#
# * 15% uplift in product awareness after just two weeks
# * 27% increase in purchase intent among exposed viewers
# * 12% sales lift in markets with highest campaign reach
# * 2.3x ROI compared to social media campaigns for the same product
#
# **Key Learning:** The frequency of exposure during binge sessions created strong brand
# recall, while the episodic creative approach maintained viewer interest despite multiple exposures.
#
# Check out [Ecommerce Marketing](https://relevantaudience.com/ecommerce-marketing) for tips to
# drive online sales.
#
# ### Financial Services: Digital Banking App
#
# **Campaign Objective:** Increase app downloads and new account openings among young
# professionals.
#
# **Strategy:**
#
# * Targeted viewers of financial and business documentaries
# * Created informative yet approachable 20-second spots highlighting unique features
# * Used QR codes for direct app download capability
# * Implemented daypart targeting focused on evening and weekend viewing
#
# **Results:**
#
# * 41% increase in app downloads during campaign period
# * 64% lower cost-per-acquisition than previous campaigns
# * 18% higher average deposit amount from Netflix-sourced customers
# * 2.5x improvement in customer retention compared to other channels
#
# **Key Learning:** The focused attention environment of Netflix led to higher comprehension
# of the app’s value proposition, while the QR code integration created a seamless path to conversion.
#
# For more strategies, visit [Lead Generation
# Service](https://relevantaudience.com/lead-generation-service).
#
# ### Travel and Hospitality: Resort Chain
#
# **Campaign Objective:** Drive bookings for vacation packages during shoulder season.
#
# **Strategy:**
#
# * Targeted viewers of travel shows and international content
# * Developed visually striking 30-second ads showcasing destinations
# * Used weather targeting to reach viewers during poor local weather conditions
# * Implemented mid-roll placements within travel-related content
#
# **Results:**
#
# * 32% increase in website visits during campaign flight
# * 28% higher booking conversion rate from Netflix-driven traffic
# * 18% increase in average booking value
# * Extended average stay by 0.7 nights compared to non-Netflix bookings
#
# **Key Learning:** Contextual alignment with travel content created high intent, while
# strategic timing during bad weather periods tapped into viewers’ escape fantasies.
#
# Explore insights from [Tourism Marketing](https://relevantaudience.com/tourism-marketing).
#
# ### Retail: Fashion Retailer
#
# **Campaign Objective:** Build awareness for seasonal collection and drive online sales.
#
# **Strategy:**
#
# * Targeted fashion-forward viewers of design shows and contemporary dramas
# * Created visually dynamic 15-second spots highlighting key collection pieces
# * Implemented interactive features allowing viewers to browse additional styles
# * Coordinated campaign with in-app collection launch
#
# **Results:**
#
# * 37% increase in brand searches during campaign period
# * 24% lift in e-commerce traffic from targeted regions
# * 19% higher average order value from Netflix-attributed customers
# * 22% increase in new customer acquisition
#
# **Key Learning:** The high-quality visual environment complemented the fashion content,
# while the immediate shopping capability through interactive features captured impulse interest.
#
# Discover more about [Content Marketing](https://relevantaudience.com/content-marketing).
#
# ### Technology: Consumer Electronics
#
# **Campaign Objective:** Launch a new smart home device line with emphasis on innovative
# features.
#
# **Strategy:**
#
# * Targeted tech enthusiasts and early adopters through content affinities
# * Created informative 30-second demonstrations of key product capabilities
# * Used household targeting to reach known technology purchasers
# * Placed ads alongside science fiction and tech-oriented content
#
# **Results:**
#
# * 44% increase in product awareness among target demographic
# * 31% lift in consideration metrics
# * 26% increase in retail partner website traffic
# * 2.1x higher conversion rate compared to YouTube campaigns
#
# **Key Learning:** The focused viewing environment allowed for more detailed feature
# explanation, resulting in better-educated prospects with higher purchase intent.
#
# For tech-related strategies, check [Digital Marketing for
# Startups](https://relevantaudience.com/digital-marketing-for-startups).
#
# ### Entertainment: Theatrical Release
#
# **Campaign Objective:** Drive opening weekend ticket sales for a major film release.
#
# **Strategy:**
#
# * Targeted viewers of similar genres and complementary content
# * Used trailer formats with countdown messaging to create urgency
# * Implemented frequency capping to prevent overexposure
# * Concentrated campaign budget in the week before release
#
# **Results:**
#
# * 29% higher ticket purchase intent among exposed viewers
# * 34% increase in trailer completion rates compared to YouTube
# * 22% of opening weekend audience reported Netflix ad exposure
# * 1.8x higher ROAS compared to traditional TV spots
#
# **Key Learning:** The ability to precisely target content-aligned audiences delivered the
# film’s message to the most receptive viewers, while the immersive format showcased the cinematic
# qualities.
