name: 'ads_performance_metrics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ads_performance_metrics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ads_performance_metrics:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

# Configuring tests - more lenient for development
tests:
  +warn_if: ">1000"
  +error_if: ">10000"

# Configuring seeds
seeds:
  ads_performance_metrics:
    +column_types:
      campaign_id: integer
      hour_ts: timestamp
      impressions: integer
      clicks: integer
      ctr: numeric(5,4)
      completion_rate: integer
      render_rate: numeric(5,4)
      fill_rate: numeric(5,4)
      response_rate: numeric(5,4)
      video_skip_rate: numeric(5,4)
      video_start: integer
      frequency: integer
      reach: integer
      requests: integer
      responses: integer
      eligible_impressions: integer
      auctions_won: integer
      viewable_impressions: integer
      audible_impressions: integer
      video_q25: integer
      video_q50: integer
      video_q75: integer
      video_q100: integer
      skips: integer
      qr_scans: integer
      interactive_engagements: integer
      spend: integer
      error_count: integer
      timeout_count: integer
